"""empty message

Revision ID: 1cb38bcb7648
Revises: 9aa4d0e049ee
Create Date: 2016-05-12 18:01:23.485893

"""

# revision identifiers, used by Alembic.
revision = '1cb38bcb7648'
down_revision = '9aa4d0e049ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'group', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    op.alter_column('group', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
